### ISSUE TITLE
Big size of git repository

### ISSUE THREAD

**Issue by githubuser0xFFFF** [ILT-HSR/SPICE#2]
Hi Lukas,

thank you for your great library. I would like to suggest something to improve the repository. I noticed, that the SPICE git repository is quite big. This is caused by the build artefacts in the build directory and by the zipped older versions (1.0.0 and 1.0.1) that are part of this repository.

I think it would be better, if you create a SPICE repository, where you initially check in the 1.0.0 version, then, update the repository to the 1.0.1 version and finally commit the 1.0.2 version. Then you have all versions properly under version control and you do not need the zipped old versions anymore.

You could provide the build artefacts in a separate repository, to keep the source repository small.

Thank you,

Uwe Kindler

**Comment by ghost** [comment]
Hi Uwe

Sorry for my slow response. I has been on vacation.

Thanks for your message and the pull request with the makefile. I will merge it. (Never learnd to create makefiles... that's the reason why i didn't make one by myself).

And the issue with the big size caused throw the builds and the zip-files: You are right, it's not good at the moment. I just don't have the experience with github. I know how version control is working (used SVN in past), but i don't see how i can mark a commit as a release and use the version control for normal working. It's important for me that people can directly get access to the current release-version and not have to find the last release-version within the verison control. I'm sure it will be possible, just have to find out how.
Short: You are right and i will change it.

And as information for you:
I plan to slim the integration interface, so that it should not be required to implement a class per command (cause in most cases it calls a function at a specific core anyway).

Proposals are always welcome. Just contact me. I have a list with possible improvements too.

I don't know where you are from. I will be at SSLA (Swiss Symposium on Lab Automation 2016, 17th march). So if you are their too, would be nice to meet you.

Regards
Lukas Müller

**Comment by githubuser0xFFFF** [comment]
Hi Lukas,

thank you for accepting my pull request.

When using GIT, creating branches and tags is a very common task and switching between branches and tags is very easy and fast - this is different from SVN. So normally in GIT it is no issue, to checkout a certain tag - e.g. tag v1.0.0 or tag v1.0.1. So it is easy to tag release versions in the version control system.

GitHub supports creating releases from Git tags: [https://help.github.com/articles/creating-releases/](https://help.github.com/articles/creating-releases/). This makes it very easy for you, to create release from Git tags and it also makes it very easy for the user to download the right release. You can even attach additional files or binaries to a release. To demonstrate this, I have created a small test repository with your SPICE source code. I checked in all versions (1.0.0, 1.0.1 and 1.0.2) and created a git tag for each version to mark a release. Then I used the GitHub releases feature to create releases from these tags. Here you can see the result:

[https://github.com/githubuser0xFFFF/GithubReleaseTest/releases](https://github.com/githubuser0xFFFF/GithubReleaseTest/releases)

The repository is small, easy and fast to clone and all releases have been created from git tags. The repository is cleaner because you have no version directory like 1.0.0 or 1.0.1 - because this is the task of the version control system.
You should definitely try this out. It is really great and it makes your repository so much easier to maintain and for your users so much easier to use.

PS: I'm from germany but unfortunately I will not be at the SSLA. What kind of PMS do you use for testing your implementation?

**Comment by ghost** [comment]
Hi Uwe

Thanks for your help.

I merged your pull request and made the changes to the file structure. Binaries and documentation are now available as downloads with the according releases. The SPI_Multidrop is at list a single project based on SPICE. It has it own repository now. Will make some crosslinks in future between them.

For testing:
- In past i used niceLAB from Equicon (currently i don't have a license anymore).
- I use Revolution from UKRobotics (works quiet well).
- I did some Tests with SOFIA (is on GitHub), but it's more a prove of concept. It just supports commands from the DeviceClasses. It doensn't works with the WSDL-File. So no specific commands are possible.

Let me know, if their are any problems, questions or wishes in the context of SPICE.

Lukas
